

ALTER TABLE event_mp.ticket_types
ADD COLUMN status VARCHAR(20) DEFAULT 'AVAILABLE',
ADD CONSTRAINT  check_status CHECK (status IN ('AVAILABLE', 'SOLD_OUT','DELETED','EXPIRED')),
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN deleted_at TIMESTAMP,
ADD COLUMN quantity_available INTEGER,
ADD CONSTRAINT  quantity_available_check CHECK (quantity_available <= quantity)
;


ALTER TABLE event_mp.tickets
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN deleted_at TIMESTAMP,
ADD CONSTRAINT  check_status CHECK (status IN ('AVAILABLE','DELETED','EXPIRED','USED'));