CREATE TABLE event_mp.roles (
    role_id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE
);


CREATE TABLE event_mp.user_roles (
    user_id INTEGER NOT NULL REFERENCES users(id),
    role_id INTEGER NOT NULL REFERENCES roles(role_id),
    assigned_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

INSERT INTO
  event_mp.roles (name, created_at, updated_at)
VALUES
  ('ADMIN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('USER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (
    'MODERATOR',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  ('EVENT_ORGANIZER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);





